version: '2'

volumes:
  postgres-data:
  
services:
  app:
    container_name: i-tracker
    image: i-tracker
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
      
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb     
    volumes:
      - postgres-data:/var/lib/postgresql/data
